/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#ff6b35',
        'primary-light': '#ffb59d',
        'primary-dark': '#5f1900',
        'primary-container': '#ff6b35',
        'secondary': '#44e2cd',
        'secondary-dark': '#03c6b2',
        'secondary-container': '#03c6b2',
        'background': '#0b1326',
        'surface': '#131b2e',
        'surface-light': '#2d3449',
        'surface-container': '#171f33',
        'surface-container-low': '#131b2e',
        'surface-container-lowest': '#060e20',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-dim': '#0b1326',
        'text-primary': '#dae2fd',
        'text-secondary': '#e1bfb5',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#e1bfb5',
        'on-background': '#dae2fd',
        'on-primary': '#5d1900',
        'on-primary-container': '#5f1900',
        'on-secondary': '#003731',
        'on-error-container': '#ffdad6',
        'error': '#ffb4ab',
        'error-bg': '#93000a',
        'error-container': '#93000a',
        'tertiary': '#b9c8de',
        'tertiary-container': '#8c9bb0',
        'outline': '#a98a80',
        'outline-variant': '#594139',
        'inverse-surface': '#dae2fd',
        'primary-fixed': '#ffdbd0',
        
        // Delivery Agent Theme Colors
        'agent-surface': '#0c160e',
        'agent-surface-dim': '#0c160e',
        'agent-surface-bright': '#323c32',
        'agent-surface-container-lowest': '#071009',
        'agent-surface-container-low': '#141e16',
        'agent-surface-container': '#18221a',
        'agent-surface-container-high': '#222c24',
        'agent-surface-container-highest': '#2d372e',
        'agent-on-surface': '#dae6d8',
        'agent-on-surface-variant': '#b9cbb9',
        'agent-inverse-surface': '#dae6d8',
        'agent-inverse-on-surface': '#29332a',
        'agent-outline': '#849585',
        'agent-outline-variant': '#3b4b3d',
        'agent-surface-tint': '#00e479',
        'agent-primary': '#f1ffef',
        'agent-on-primary': '#003919',
        'agent-primary-container': '#00ff88',
        'agent-on-primary-container': '#007139',
        'agent-inverse-primary': '#006d37',
        'agent-secondary': '#ffb1c7',
        'agent-on-secondary': '#650032',
        'agent-secondary-container': '#ff4994',
        'agent-on-secondary-container': '#59002b',
        'agent-tertiary': '#fffaf7',
        'agent-on-tertiary': '#3d2f00',
        'agent-tertiary-container': '#ffdb79',
        'agent-on-tertiary-container': '#795f01',
        'agent-error': '#ffb4ab',
        'agent-on-error': '#690005',
        'agent-error-container': '#93000a',
        'agent-on-error-container': '#ffdad6',
        'agent-primary-fixed': '#60ff99',
        'agent-primary-fixed-dim': '#00e479',
        'agent-on-primary-fixed': '#00210c',
        'agent-on-primary-fixed-variant': '#005228',
        'agent-secondary-fixed': '#ffd9e2',
        'agent-secondary-fixed-dim': '#ffb1c7',
        'agent-on-secondary-fixed': '#3e001d',
        'agent-on-secondary-fixed-variant': '#8e0049',
        'agent-tertiary-fixed': '#ffe08d',
        'agent-tertiary-fixed-dim': '#e5c364',
        'agent-on-tertiary-fixed': '#241a00',
        'agent-on-tertiary-fixed-variant': '#584400',
        'agent-background': '#0c160e',
        'agent-on-background': '#dae6d8',
        'agent-surface-variant': '#2d372e',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        'display-md': ["Inter"],
        'display-lg': ["Inter"],
        'label-caps': ["Inter"],
        'body-md': ["Inter"],
        'body-lg': ["Inter"]
      },
      fontSize: {
        "display-md": ["24px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "display-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "body-lg": ["16px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}]
      },
      spacing: {
        "stack-sm": "8px",
        "unit": "8px",
        "card-padding": "24px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-margin": "32px",
        "gutter": "24px"
      },
      boxShadow: {
        'neomorphic': '20px 20px 60px rgba(0, 0, 0, 0.4), -5px -5px 30px rgba(30, 41, 59, 0.5)',
        'neomorphic-inset': 'inset 2px 2px 5px rgba(0, 0, 0, 0.4), inset -2px -2px 5px rgba(30, 41, 59, 0.3)',
        'button-glow': 'inset 0 1px 1px rgba(255, 255, 255, 0.3), 0 4px 15px rgba(255, 107, 53, 0.3)',
      },
      backdropBlur: {
        'glass': '24px',
      },
    },
  },
  plugins: [],
}
