/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Crave Vibrant Design System - Light Theme
        'inverse-on-surface': '#ebf2f4',
        'tertiary-fixed': '#ffe07e',
        'primary-container': '#dc3214',
        'secondary-fixed': '#6bfe9c',
        'surface': '#f4fafd',
        'on-primary': '#ffffff',
        'primary': '#b51c00',
        'surface-tint': '#ba1c00',
        'tertiary-fixed-dim': '#ebc31d',
        'surface-container': '#e8eff1',
        'on-primary-container': '#fffbff',
        'on-primary-fixed': '#3e0400',
        'tertiary-container': '#cca700',
        'tertiary': '#725c00',
        'inverse-surface': '#2b3234',
        'on-error-container': '#93000a',
        'surface-container-high': '#e2e9ec',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#4d3e00',
        'surface-container-low': '#eef5f7',
        'on-surface': '#161d1f',
        'secondary-container': '#6bfe9c',
        'on-primary-fixed-variant': '#8e1300',
        'inverse-primary': '#ffb4a5',
        'on-error': '#ffffff',
        'error': '#ba1a1a',
        'secondary-fixed-dim': '#4ae183',
        'surface-container-highest': '#dde4e6',
        'outline-variant': '#e5bdb6',
        'on-secondary-fixed-variant': '#005228',
        'outline': '#916f69',
        'on-tertiary-fixed': '#231b00',
        'surface-variant': '#dde4e6',
        'on-secondary-container': '#00743a',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#564500',
        'surface-bright': '#f4fafd',
        'background': '#f4fafd',
        'error-container': '#ffdad6',
        'surface-dim': '#d4dbdd',
        'on-secondary-fixed': '#00210c',
        'on-background': '#161d1f',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#5c403a',
        'secondary': '#006d37',
        'primary-fixed': '#ffdad3',
        'primary-fixed-dim': '#ffb4a5',
      },
      fontFamily: {
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'label-lg': ['Work Sans', 'sans-serif'],
        'label-sm': ['Work Sans', 'sans-serif'],
        'sans': ['Work Sans', 'sans-serif'],
        'heading': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        'gutter': '16px',
        'unit': '4px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm': '0.25rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'level-1': '0 4px 12px rgba(181, 28, 0, 0.06)',
        'level-2': '0 8px 20px rgba(181, 28, 0, 0.10)',
        'interactive': '0 6px 16px rgba(181, 28, 0, 0.08)',
        'glow': '0 0 20px rgba(181, 28, 0, 0.3)',
        'glow-strong': '0 0 30px rgba(181, 28, 0, 0.5)',
      },
      backdropBlur: {
        'glass': '10px',
        'glass-strong': '20px',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-in-left': 'slideInLeft 0.4s ease-out',
        'slide-in-right': 'slideInRight 0.4s ease-out',
        'slide-in-bottom': 'slideInBottom 0.4s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'float': 'float 3s ease-in-out infinite',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInBottom: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(181, 28, 0, 0.3)' },
          '50%': { boxShadow: '0 0 30px rgba(181, 28, 0, 0.5)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
      },
    },
  },
  plugins: [],
}
